---
- hosts: loadbalancer
  become: true
  tasks:
    - name: verify nginx status
      command: service nginx status

    - name: verify nginx is listening on 8010
      wait_for: port=8010 timeout=30

- hosts: app01
  become: true
  tasks:
    - name: verify apache2 status
      command: service apache2 status

    - name: verify apache is listening on 8020
      wait_for: port=8020 timeout=30

- hosts: app02
  become: true
  tasks:
    - name: verify apache2 status
      command: service apache2 status

    - name: verify apache is listening on 8030
      wait_for: port=8030 timeout=30

- hosts: database
  become: true
  tasks:
    - name: verify mysql status
      command: service mysql status

    - name: verify mysql is listening on 33064
      wait_for: port=33064 timeout=30

- hosts: control
  tasks:
    - name: verify end-to-end response
      uri: url=http://{{item}} return_content=yes
      with_items: groups.loadbalancer
      register: lb_index

    - fail: msg="index failed to return content"
      when: "'Hello, from sunny' not in item.content"
      with_items: "{{lb_index.results}}"